{
 "title": "Localnet - CCTXs analytics",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "network", "label": "network", "query": "mainnet,testnet" }
  ]
 },
 "panels": [
  {
   "title": "CCTX success rate per chain (excludes 100% chains)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zetachain_exporter_chain_nonces{network=\"$network\"}",
     "legendFormat": "{{chain}}"
    },
    {
     "rawSql": "SELECT \n    chain_id AS chain,\n    count(*) AS problematic_count\nFROM problematic_cctxs.${network}_cctxs\nWHERE $__timeFilter(datetime)\nGROUP BY chain_id\nORDER BY chain_id"
    }
   ]
  },
  {
   "title": "Total CCTXs per chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zetachain_exporter_chain_nonces{network=\"$network\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Total CCTXs per chain in period of time (max 30d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zetachain_exporter_chain_nonces{network=\"$network\"} - zetachain_exporter_chain_nonces{network=\"$network\"} offset $__range",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "All chains missed trackers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(tx_type = 'inbound' ? 1 : 0) AS inbound,\n    sum(tx_type = 'outbound' ? 1 : 0) AS outbound,\n    count(*) AS total_trackers\nFROM problematic_cctxs.${network}_cctxs\nWHERE $__timeFilter(datetime)\n"
    }
   ]
  },
  {
   "title": "Avg Outbound CCTX tracker duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "zetachain_exporter_outbound_cctx_tracker_duration{network=\"$network\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Trackers by chain",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n    toDate(datetime) AS day,\n    chain_id,\n    sum(tx_type = 'inbound' ? 1 : 0) AS inbound,\n    sum(tx_type = 'outbound' ? 1 : 0) AS outbound\nFROM problematic_cctxs.${network}_cctxs\nWHERE $__timeFilter(datetime)\nGROUP BY\n    day,\n    chain_id\nORDER BY\n    day ASC,\n    chain_id ASC\n"
    }
   ]
  },
  {
   "title": "Total Missed Trackers (Inbound + Outbound)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    chain_id,\n    count(*) AS total_trackers\nFROM problematic_cctxs.${network}_cctxs\nWHERE $__timeFilter(datetime)\nGROUP BY\n    chain_id\nORDER BY\n    total_trackers DESC\n"
    }
   ]
  },
  {
   "title": "Total Missed Inbound Trackers (excludes zeroes)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    chain_id,\n    sum(tx_type = 'inbound' ? 1 : 0) AS inbound\nFROM problematic_cctxs.${network}_cctxs\nWHERE $__timeFilter(datetime)\nGROUP BY\n    chain_id\nORDER BY\n    inbound DESC\n"
    }
   ]
  },
  {
   "title": "Total Missed Outbound Trackers (excludes zeroes)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    chain_id,\n    sum(tx_type = 'outbound' ? 1 : 0) AS outbound\nFROM problematic_cctxs.${network}_cctxs\nWHERE $__timeFilter(datetime)\nGROUP BY\n    chain_id\nORDER BY\n    outbound DESC\n"
    }
   ]
  }
 ]
}