{
 "title": "Ethereum Wallet Monitor",
 "description": "Graph Ethereum Wallet Balances",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": "label_values(eth_balance, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Addresses Logged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_total_addresses" }
   ]
  },
  {
   "title": "Top 5 Balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(5, eth_balance)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total ETH 1 Hour Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance_total - eth_balance_total offset 1m) / eth_balance_total"
    }
   ]
  },
  {
   "title": "Total Load Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_load_seconds" }
   ]
  },
  {
   "title": "Total ETH 24 Hour Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance_total - eth_balance_total offset 24h) / eth_balance_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<center><span style=\"font-size: 3rem\">${name}</span></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "${name} Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "locale", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "eth_balance{name=\"${name}\"}",
     "legendFormat": "${name} ETH"
    }
   ]
  },
  {
   "title": "${name} ETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "${name} ETH 1 Hour Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance{name=\"${name}\"} - eth_balance{name=\"${name}\"} offset 1h) / eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "${name} ETH 24 Hour Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance{name=\"${name}\"} - eth_balance{name=\"${name}\"} offset 24h) / eth_balance{name=\"${name}\"}"
    }
   ]
  },
  {
   "title": "${name} ETH Week Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(eth_balance{name=\"${name}\"} - eth_balance{name=\"${name}\"} offset 7d) / eth_balance{name=\"${name}\"}"
    }
   ]
  }
 ]
}