{
 "title": "Localnet - Gas Stats & Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h" },
   { "name": "network", "query": { "query": "localnet" } }
  ]
 },
 "panels": [
  { "title": "Zetachain Gas Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gas Used Per Block (azeta)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "zetachain_exporter_gas_per_block"
    }
   ]
  },
  {
   "title": "Zetachain Current Gas Price (azeta)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by(chain) (zetachain_exporter_current_gas_price)"
    }
   ]
  },
  {
   "title": "Zetachain Base Gas Fee (azeta)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_base_gas_fee{denom=\"azeta\"})"
    }
   ]
  },
  {
   "title": "Zetachain Gas Elasticity Multiplier",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(chain) (zetachain_exporter_gas_elasticity_multiplier)"
    }
   ]
  },
  {
   "title": "Zetachain Gas Stability Pool Balances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "zetachain_exporter_gas_pool_balance",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "Uniswap V2 Liquidity Pools by Pair Address",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (zetachain_exporter_uniswap_reserves)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tendermint Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Transactions Per Block (est)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "zetachain_exporter_block_transactions"
    }
   ]
  },
  {
   "title": "Tendermint Failed Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "tendermint_mempool_failed_txs" }
   ]
  }
 ]
}