{
 "title": "Inbound Vote Metrics",
 "description": "A Grafana dashboard for monitoring inbound vote metrics in ZetaChain zetaclient",
 "tags": [
  "ZetaChain",
  "InboundVotes",
  "Zetaclient"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain",
    "label": "Chain",
    "query": "label_values(zetaclient_inbound_votes_block_scan_total, chain)"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Block Scan Observations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_inbound_votes_block_scan_total)"
    }
   ]
  },
  {
   "title": "Total Zetacore Tracker Observations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_inbound_observations_tracker_total{internal=\"false\"})"
    }
   ]
  },
  {
   "title": "Total Successful",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_inbound_votes_successful_total)"
    }
   ]
  },
  {
   "title": "Active internal trackers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_internal_trackers_active)"
    }
   ]
  },
  {
   "title": "Chain Specific details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Observations by Chain Block Scan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_votes_block_scan_total",
     "legendFormat": "{{chain}} - Block Scan"
    }
   ]
  },
  {
   "title": "Inbound Observations by Chain Internal Trackers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_observations_tracker_total{internal=\"true\"}",
     "legendFormat": "{{chain}} - Internal Tracker"
    }
   ]
  },
  {
   "title": "Inbound Observations by Chain Zetacore Trackers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_observations_tracker_total{internal=\"false\"}",
     "legendFormat": "{{chain}} - Zetacore Tracker"
    }
   ]
  },
  {
   "title": "Inbound Success Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ethereum - Success Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  zetaclient_inbound_votes_successful_total{chain=\"goerli_localnet\"} / \n  (\n    zetaclient_inbound_votes_block_scan_total{chain=\"goerli_localnet\"} + \n    (zetaclient_inbound_observations_tracker_total{chain=\"goerli_localnet\", internal=\"false\"} or zetaclient_inbound_votes_block_scan_total{chain=\"goerli_localnet\"} * 0)\n  )\n) * 100"
    }
   ]
  },
  {
   "title": "Bitcoin - Success Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(zetaclient_inbound_votes_successful_total{chain=\"btc_regtest\"} / \n(zetaclient_inbound_votes_block_scan_total{chain=\"btc_regtest\"} + \nzetaclient_inbound_observations_tracker_total{chain=\"btc_regtest\", internal=\"false\"})) * 100"
    }
   ]
  },
  {
   "title": "Transaction metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Votes by Gas Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_votes_posted_500k_gas_limit_total",
     "legendFormat": "{{chain}} - 500K Gas Limit"
    },
    {
     "expr": "zetaclient_inbound_votes_posted_7m_gas_limit_total",
     "legendFormat": "{{chain}} - 7M Gas Limit"
    }
   ]
  },
  {
   "title": "Internal trackers added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_transactions_added_to_internal_tracker_total",
     "legendFormat": "{{chain}} - Added to Tracker"
    }
   ]
  }
 ]
}