{
 "title": "Inbound Vote Metrics - Zetaclient0",
 "description": "A Grafana dashboard for monitoring inbound vote metrics for localnet zetaclient0 instance.",
 "tags": [
  "ZetaChain",
  "InboundVotes",
  "Zetaclient0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain",
    "label": "Chain",
    "query": "label_values(zetaclient_inbound_votes_block_scan_total{instance=\"172.20.0.21:8886\"}, chain)"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Overview - Zetaclient0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Block Scan Observations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_inbound_votes_block_scan_total{instance=\"172.20.0.21:8886\"})"
    }
   ]
  },
  {
   "title": "Total Zetacore Tracker Observations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_inbound_observations_tracker_total{internal=\"false\", instance=\"172.20.0.21:8886\"})"
    }
   ]
  },
  {
   "title": "Total Successful",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_inbound_votes_successful_total{instance=\"172.20.0.21:8886\"})"
    }
   ]
  },
  {
   "title": "Total Transactions Added to Internal Tracker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_transactions_added_to_internal_tracker_total{instance=\"172.20.0.21:8886\"})"
    }
   ]
  },
  {
   "title": "Active Internal Trackers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zetaclient_internal_trackers_active{instance=\"172.20.0.21:8886\"})"
    }
   ]
  },
  {
   "title": "Chain Specific details - Zetaclient0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Observations by Chain Block Scan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_votes_block_scan_total{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - Block Scan"
    }
   ]
  },
  {
   "title": "Inbound Observations by Chain Internal Trackers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_observations_tracker_total{internal=\"true\", instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - Internal Tracker"
    }
   ]
  },
  {
   "title": "Inbound Observations by Chain Zetacore Trackers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_observations_tracker_total{internal=\"false\", instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - Zetacore Tracker"
    }
   ]
  },
  {
   "title": "Successful Votes by Chain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_votes_successful_total{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - Successful Votes"
    }
   ]
  },
  {
   "title": "Inbound Success Rate - Zetaclient0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ethereum - Success Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  zetaclient_inbound_votes_successful_total{chain=\"goerli_localnet\", instance=\"172.20.0.21:8886\"} + \n  (zetaclient_transactions_added_to_internal_tracker_total{chain=\"goerli_localnet\", instance=\"172.20.0.21:8886\"} or zetaclient_inbound_votes_successful_total{chain=\"goerli_localnet\", instance=\"172.20.0.21:8886\"} * 0) - \n  (zetaclient_internal_trackers_active{chain=\"goerli_localnet\", instance=\"172.20.0.21:8886\"} or zetaclient_inbound_votes_successful_total{chain=\"goerli_localnet\", instance=\"172.20.0.21:8886\"} * 0)\n) / \nzetaclient_inbound_votes_block_scan_total{chain=\"goerli_localnet\", instance=\"172.20.0.21:8886\"} * 100"
    }
   ]
  },
  {
   "title": "Bitcoin - Success Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    zetaclient_inbound_votes_successful_total{chain=\"btc_regtest\", instance=\"172.20.0.21:8886\"} + \n    on(instance) group_left() (zetaclient_transactions_added_to_internal_tracker_total{chain=\"btc_regtest\", instance=\"172.20.0.21:8886\"} or absent(zetaclient_transactions_added_to_internal_tracker_total{chain=\"btc_regtest\", instance=\"172.20.0.21:8886\"}) * 0) - \n    on(instance) group_left() (zetaclient_internal_trackers_active{chain=\"btc_regtest\", instance=\"172.20.0.21:8886\"} or absent(zetaclient_internal_trackers_active{chain=\"btc_regtest\", instance=\"172.20.0.21:8886\"}) * 0)\n  ) / \n  zetaclient_inbound_votes_block_scan_total{chain=\"btc_regtest\", instance=\"172.20.0.21:8886\"}\n) * 100"
    }
   ]
  },
  {
   "title": "Sui - Success Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  zetaclient_inbound_votes_successful_total{chain=\"sui_localnet\", instance=\"172.20.0.21:8886\"} + \n  (zetaclient_transactions_added_to_internal_tracker_total{chain=\"sui_localnet\", instance=\"172.20.0.21:8886\"} or zetaclient_inbound_votes_successful_total{chain=\"sui_localnet\", instance=\"172.20.0.21:8886\"} * 0) - \n  (zetaclient_internal_trackers_active{chain=\"sui_localnet\", instance=\"172.20.0.21:8886\"} or zetaclient_inbound_votes_successful_total{chain=\"sui_localnet\", instance=\"172.20.0.21:8886\"} * 0)\n) / \nzetaclient_inbound_votes_block_scan_total{chain=\"sui_localnet\", instance=\"172.20.0.21:8886\"} * 100"
    }
   ]
  },
  {
   "title": "Solana - Success Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  zetaclient_inbound_votes_successful_total{chain=\"solana_localnet\", instance=\"172.20.0.21:8886\"} + \n  (zetaclient_transactions_added_to_internal_tracker_total{chain=\"solana_localnet\", instance=\"172.20.0.21:8886\"} or zetaclient_inbound_votes_successful_total{chain=\"solana_localnet\", instance=\"172.20.0.21:8886\"} * 0) - \n  (zetaclient_internal_trackers_active{chain=\"solana_localnet\", instance=\"172.20.0.21:8886\"} or zetaclient_inbound_votes_successful_total{chain=\"solana_localnet\", instance=\"172.20.0.21:8886\"} * 0)\n) / \nzetaclient_inbound_votes_block_scan_total{chain=\"solana_localnet\", instance=\"172.20.0.21:8886\"} * 100"
    }
   ]
  },
  {
   "title": "Internal Tracker Metrics - Zetaclient0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Internal Trackers by Chain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_internal_trackers_active{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - Active Trackers"
    }
   ]
  },
  {
   "title": "Internal Trackers Added by Chain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_transactions_added_to_internal_tracker_total{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - Added to Tracker"
    }
   ]
  },
  {
   "title": "Transaction metrics - Zetaclient0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Votes by Gas Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "zetaclient_inbound_votes_posted_500k_gas_limit_total{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - 500K Gas Limit"
    },
    {
     "expr": "zetaclient_inbound_votes_posted_7m_gas_limit_total{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "{{chain}} - 7M Gas Limit"
    }
   ]
  }
 ]
}