{
 "title": "Localnet - Rate Limiter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h" },
   { "name": "network", "query": { "query": "localnet" } }
  ]
 },
 "panels": [
  { "title": "Rate Limiter Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate Limiter Enabled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "zetachain_exporter_rate_limiter_metrics{name=\"enabled\"}",
     "legendFormat": "Enabled"
    }
   ]
  },
  {
   "title": "Rate Limiter Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "zetachain_exporter_rate_limiter_metrics{name=\"rate_limit_exceeded\"}",
     "legendFormat": "Rate Limit Exceeded"
    }
   ]
  },
  {
   "title": "Current Withdraw Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "zetachain_exporter_rate_limiter_metrics{name=\"current_withdraw_rate\"}",
     "legendFormat": "Withdraw Rate"
    },
    {
     "expr": "zetachain_exporter_rate_limiter_metrics{name=\"rate\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Transaction Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cometbft_consensus_latest_block_height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zetachain Protocol Fee (azeta)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zetachain_exporter_zeta_count{name=\"zetachain_protocol_fee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZETA Tokens Used for Emissions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ZETA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " - zetachain_exporter_emission_balance{name=\"emission_module_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aborted Zeta (azeta)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "zetachain_exporter_zeta_count{name=\"aborted_zeta_amount\"}",
     "legendFormat": "azeta"
    }
   ]
  },
  {
   "title": "Transactions Per Block (est)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "zetachain_exporter_block_transactions"
    }
   ]
  },
  {
   "title": "Transactions Per Block (est)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "zetachain_exporter_block_transactions"
    }
   ]
  },
  {
   "title": "Tendermint Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Zetachain Pending Chain Nonces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg by(chain, type) (zetachain_exporter_pending_chain_nonces{type=\"pending\"})"
    }
   ]
  },
  {
   "title": "Zetachain Emission Address Balances (azeta)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg by(name) (zetachain_exporter_emission_balance)"
    }
   ]
  },
  {
   "title": "Total CCTX ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(chain, name) (zetachain_exporter_chain_nonces)"
    }
   ]
  },
  {
   "title": "Tendermint Failed Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    { "expr": "cometbft_mempool_failed_txs" }
   ]
  }
 ]
}