{
 "title": "Signer Sync (Localnet)",
 "tags": [ "localnet" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" }
  ]
 },
 "panels": [
  {
   "title": "Pending CCTXs per chain",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(chain) (zetaclient_pending_txs_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signer Result Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg by(result) (rate(zetaclient_sign_latency_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Individual Signer Total Rate",
   "type": "timeseries",
   "description": "This indicates whether signers are synced",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(job) (max by(job, result) (rate(zetaclient_sign_latency_sum[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active keysigns",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max by(job) (zetaclient_num_active_message_signs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending TXs signer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(job) (max by(job, chain) (zetaclient_pending_txs_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block latency std deviation",
   "type": "timeseries",
   "description": "stddev(zetaclient_core_block_latency)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "stddev(zetaclient_core_block_latency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effective Block latency std deviation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "stddev (zetaclient_core_block_latency + zetaclient_core_block_latency_sleep)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "max by(job) (zetaclient_core_block_latency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effective Block latency",
   "type": "timeseries",
   "description": "core_block_latency + core_block_latency_sleep",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "max by (job) (zetaclient_core_block_latency + zetaclient_core_block_latency_sleep)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}