{
 "title": "Localnet - Transaction Data",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h" },
   { "name": "network", "query": { "query": "localnet" } }
  ]
 },
 "panels": [
  {
   "title": "Inbound Transactions Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ERC20 Custody Contract Inbound Monitoring",
   "type": "timeseries",
   "description": "1 means no missed inbound observations. 0 means there are missed observations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "zetachain_exporter_inbound_observation_status{contract=\"custody\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Gateway Contract Inbound Monitoring",
   "type": "timeseries",
   "description": "1 means no missed inbound observations. 0 means there are missed observations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "zetachain_exporter_inbound_observation_status{contract=\"gateway\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "TSS Address Inbound Monitoring",
   "type": "timeseries",
   "description": "1 means no missed inbound observations. 0 means there are missed observations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "zetachain_exporter_inbound_observation_status{contract=\"TSS\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  { "title": "Cross-Chain Transaction Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pending Outbound Nonces ",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(chain) (zetachain_exporter_pending_chain_nonces{network=\"$network\", type=\"pending\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Pending Outbound Nonces",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg by(chain, type) (zetachain_exporter_pending_chain_nonces{type=\"pending\"})"
    }
   ]
  },
  {
   "title": "Long-Lived Pending CCTXs",
   "type": "timeseries",
   "description": "CCTXs that have been pending for longer than 30 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "zetachain_exporter_pending_cctx_count{network=\"$network\", duration=\"long_lived\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Pending Outbound Nonces - Change In Last ",
   "type": "bargauge",
   "description": "This shows the change in pending nones during the range set or the dashboard. If it says 30 minutes in the top right then this is the change between pending nonce at the start of the 30 minutes and now. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(zetachain_exporter_pending_chain_nonces{network=\"$network\", type=\"pending\"}[$__range])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Zetachain Gas Stability Pool Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "zetachain_exporter_gas_pool_balance{network=\"$network\"}",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "Total Completed CCTX ",
   "type": "bargauge",
   "description": "Total CCTX Count Since Network Genesis",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(chain, name) (zetachain_exporter_chain_nonces{network=\"$network\"})"
    }
   ]
  },
  { "title": "Non-CCTX Transaction Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Tendermint Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{network=\"$network\"}"
    }
   ]
  },
  {
   "title": "Tendermint Failed Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{network=\"$network\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transactions Per Block (est)",
   "type": "timeseries",
   "description": "This is an estimated value only. For more accurate historical data you should use indexed data. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "zetachain_exporter_block_transactions{network=\"$network\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Outbound CCTX Tracker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Long-Lived Outbound CCTX Tracker Count",
   "type": "timeseries",
   "description": "Count of all Outbound CCTX Trackers per chain that are older than 30 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "trackers" } },
   "targets": [
    {
     "expr": "zetachain_exporter_outbound_cctx_tracker_count{network=\"$network\", duration=\"long_lived\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Outbound CCTX Tracker Count",
   "type": "timeseries",
   "description": "Count of all Outbound CCTX Trackers per chain",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "trackers" } },
   "targets": [
    {
     "expr": "zetachain_exporter_outbound_cctx_tracker_count{network=\"$network\", duration=\"overall\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Avg Duration of CCTX Outbound Trackers",
   "type": "timeseries",
   "description": "Avg time duration of CCTX Outbound Tracker Per Chain",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "zetachain_exporter_outbound_cctx_tracker_duration{network=\"$network\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  }
 ]
}