{
 "title": "Localnet - TSS Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h" },
   { "name": "network", "query": { "query": "localnet" } }
  ]
 },
 "panels": [
  { "title": "TSS Key Sign Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TSS Join Party Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(job) (Tss_Tss_joinparty_time)"
    }
   ]
  },
  {
   "title": "TSS Join Party - Success Rate per Job",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(Tss_Tss_join_party{result=\"success\"}[$__rate_interval])) by (job) / sum(rate(Tss_Tss_join_party[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TSS Keysign - Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(job) (Tss_Tss_keysign_time)",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "TSS Keysign - Success Rate per Job",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(Tss_Tss_keysign{status=\"success\"}[$__rate_interval])) by (job) / sum(rate(Tss_Tss_keysign[$__rate_interval])) by (job)",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "TSS Node Blame Count",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg by(pubkey) (zetaclient_tss_node_blame_count)"
    }
   ]
  },
  {
   "title": "TSS KeyGen Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "avg by(job) (Tss_Tss_keygen_time)"
    }
   ]
  },
  {
   "title": "Concurrent Key Signs (Max)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "keysigns" } },
   "targets": [
    {
     "expr": "max by(job) (zetaclient_num_active_message_signs)",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "Concurrent Key Signs (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "keysigns" } },
   "targets": [
    {
     "expr": "avg by(job) (zetaclient_num_active_message_signs)",
     "legendFormat": "{{denom}}"
    }
   ]
  }
 ]
}