{
 "title": "Localnet - Zetaclient Orchestrator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "network", "label": "network", "query": { "query": "localnet" } }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Orchestrator Metrics\n\nObserver-Signers record metrics for each task invoked\n\n- **zetaclient_scheduler_task_invocations_total** (counter)\n- **zetaclient_scheduler_task_duration_seconds** (histogram)\n"
   }
  },
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "Available labels:\n\n- `status`: [ok, failed, skipped]\n- `task_group`: `$chain:$chainId` (eg `evm:1`)\n- `task_name`: eg *observe_inbounds*\n- Other regular labels (job, network, ...)\n"
   }
  },
  { "title": "Successful Task Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Count per Validator (5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(zetaclient_scheduler_task_invocations_total{network=\"$network\",status=\"ok\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator / Task P90",
   "type": "table",
   "description": "Provides last(p90) of successfull task invocations per validator+chain+task",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "label_join (\nhistogram_quantile(0.9,\n    sum by (job, task_group, task_name, le) (\n        increase(zetaclient_scheduler_task_duration_seconds_bucket{status=\"ok\", network=\"$network\"}[$__range])\n    )\n),\n  \"task_id\", \":\", \"task_group\", \"task_name\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Task Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Failures per Chain/Task",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(task_group, task_name) (increase(zetaclient_scheduler_task_invocations_total{network=\"$network\",status=\"failed\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures per Validator (5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by(job) (increase(zetaclient_scheduler_task_invocations_total{network=\"$network\", status=\"failed\"}[5m]))",
     "legendFormat": "{{job}} - {{status}}"
    }
   ]
  },
  {
   "title": "Failures per Chain (5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(task_group) (increase(zetaclient_scheduler_task_invocations_total{network=\"$network\", status=\"failed\"}[5m]))",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Failures per Task (5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum by(task_name) (increase(zetaclient_scheduler_task_invocations_total{network=\"$network\", status=\"failed\"}[5m]))",
     "legendFormat": "{{task_group}}"
    }
   ]
  }
 ]
}