{
 "title": "Localnet - ZRC20 Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "localnet" },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(zetachain_exporter_bonded_tokens,network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Token Supply", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Locked ZETA Tokens on ETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_locked_amount{network=\"$network\", name=\"ZetaConnectorContractETH\"})",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "Unlocked ZETA Tokens  on ETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(2100000000-zetachain_exporter_locked_amount{network=\"$network\", name=\"ZetaConnectorContractETH\"})",
     "legendFormat": "Unlocked"
    }
   ]
  },
  {
   "title": "ZETA Token Supply on ZetaChain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_cosmos_supply{network=\"$network\"} / 1e+18)",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "ZETA Token Supply on BSC Chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_token_supply{network=\"$network\", name=\"ZetaTokenContractBSC\"})",
     "legendFormat": "Unlocked"
    }
   ]
  },
  {
   "title": "WZETA Token Supply on ZetaChain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_token_supply{network=\"$network\", name=\"ZetaTokenContract\"})",
     "legendFormat": "Unlocked"
    }
   ]
  },
  {
   "title": "Locked ZETA Tokens on ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_locked_amount{network=\"$network\", name=\"ZetaConnectorContractETH\"})",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "Unlocked ZETA Tokens on ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(2100000000-zetachain_exporter_locked_amount{network=\"$network\", name=\"ZetaConnectorContractETH\"})",
     "legendFormat": "Unlocked"
    }
   ]
  },
  {
   "title": "WZETA Token Supply on ZetaChain",
   "type": "timeseries",
   "description": "Wrapped Zeta Token Supply on ZetaChain",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_token_supply{network=\"$network\", name=\"ZetaTokenContract\"})",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "ZETA Token Supply on ZetaChain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_cosmos_supply{network=\"$network\"} / 1e+18)",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "ZETA Token Supply on BSC Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(zetachain_exporter_token_supply{network=\"$network\", name=\"ZetaTokenContractBSC\"})",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "Bonded Token Ratio on ZetaChain Network",
   "type": "timeseries",
   "description": "bonded tokens / total supply of Zeta tokens on ZetaChain Network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "zetachain_exporter_bonded_tokens{network=\"$network\", job=\"zetachain-exporter-mainnet\"} / zetachain_exporter_cosmos_supply{network=\"$network\", job=\"zetachain-exporter-mainnet\"}",
     "legendFormat": "Ratio"
    }
   ]
  },
  { "title": "Cross Chain Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Zetachain Unique Foreign Coins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (zetachain_exporter_balance{chain=\"101\", name!=\"nonce-checker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC Cross-chain Token Monitor ($BTC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "zetachain_exporter_crosschain_balance{network=\"$network\", denom=\"BTC.BTC\"}",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "ETH Cross-chain Token Monitor ($ETH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "zetachain_exporter_crosschain_balance{network=\"$network\", denom=\"ETH.ETH\"}",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "BNB Cross-chain Token Monitor ($BNB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "BNB" } },
   "targets": [
    {
     "expr": "zetachain_exporter_crosschain_balance{network=\"$network\", denom=\"BNB.BSC\"}",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "POL Cross-chain Token Monitor ($POL)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "POL" } },
   "targets": [
    {
     "expr": "zetachain_exporter_crosschain_balance{network=\"$network\", denom=\"POL.POLYGON\"}",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "USDT-ETH Cross-chain Token Monitor ($USDT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "USDT" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "USDC-ETH Cross-chain Token Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "USDT-BSC Cross-chain Token Monitor ($USDT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "USDT" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "USDC-BSC Cross-chain Token Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "USDT.POL Cross-chain Token Monitor ($USDT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "USDT" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "USDC.POL Cross-chain Token Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "SHIB.ETH Cross-chain Token Monitor ($SHIB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "SHIB" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "PEPE.ETH Cross-chain Token Monitor ($PEPE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "PEPE" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "ULTI.ETH Cross-chain Token Monitor ($ULTI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ULTI" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "DAI.ETH Cross-chain Token Monitor ($DAI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "DAI" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "USDC.BASE Cross-chain Token Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  { "title": "Foreign Token Liquidity Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "BTC.BTC Liquidity Cap VS. Token Supply Monitor ($BTC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"BTC.BTC\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"BTC.BTC\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "ETH.ETH Liquidity Cap VS. Token Supply Monitor ($ETH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"ETH.ETH\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"ETH.ETH\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "BNB.BSC Liquidity Cap VS. Token Supply Monitor ($BNB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "BNB" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"BNB.BSC\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"BNB.BSC\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "POL.POLYGON Liquidity Cap VS. Token Supply Monitor ($POL)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "POL" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"POL.POLYGON\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"POL.POLYGON\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "ETH.BASE Liquidity Cap VS. Token Supply Monitor ($BASE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "BASE" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"ETH.BASE\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"ETH.BASE\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDC.ETH Liquidity Cap VS. Token Supply Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDC.ETH\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDC.ETH\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDT.ETH Liquidity Cap VS. Token Supply Monitor ($USDT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "USDT" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDT.ETH\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDT.ETH\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDC.BSC Liquidity Cap VS. Token Supply Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDC.BSC\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDC.BSC\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDT.BSC Liquidity Cap VS. Token Supply Monitor ($USDT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "USDT" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDT.BSC\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDT.BSC\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDC.POL Liquidity Cap VS. Token Supply Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDC.POL\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDC.POL\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDT.POL Liquidity Cap VS. Token Supply Monitor ($USDT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "USDT" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDT.POL\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDT.POL\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "USDC.BASE Liquidity Cap VS. Token Supply Monitor ($USDC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "USDC" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"USDC.BASE\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"USDC.BASE\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "SHIB.ETH Liquidity Cap VS. Token Supply Monitor ($SHIB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "SHIB" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"SHIB.ETH\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"SHIB.ETH\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "PEPE.ETH Liquidity Cap VS. Token Supply Monitor ($PEPE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "PEPE" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"PEPE.ETH\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"PEPE.ETH\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "DAI.ETH Liquidity Cap VS. Token Supply Monitor ($DAI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "DAI" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"DAI.ETH\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"DAI.ETH\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  },
  {
   "title": "ULTI.ETH Liquidity Cap VS. Token Supply Monitor ($ULTI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ULTI" } },
   "targets": [
    {
     "expr": "zetachain_exporter_liquidity_cap{symbol=\"ULTI.ETH\", network=\"$network\"}",
     "legendFormat": "liquidity_cap"
    },
    {
     "expr": "zetachain_exporter_token_supply{symbol=\"ULTI.ETH\", network=\"$network\"}",
     "legendFormat": "token_supply"
    }
   ]
  }
 ]
}