FROM ubuntu:22.04

RUN apt-get update -y && apt-get upgrade -y \
    && apt install build-essential  make gcc jq curl -y

WORKDIR /go/delivery
COPY ./zetaclientd /usr/bin/
COPY ./zetacored /usr/bin/
COPY ./build ./zeta-node/build
COPY ./deploy ./zeta-node/deploy

RUN useradd -ms /bin/bash zetachain
RUN chown -R zetachain:zetachain  /usr/bin/zetacored  /usr/bin/zetaclientd /go/delivery
USER zetachain

ENV SHELL /bin/bash
EXPOSE 8400
ENTRYPOINT ["bash"]