FROM golang:alpine as smoketestbuilder

RUN apk --no-cache add  make  git build-base  jq


ENV GOPATH /go
WORKDIR /go/delivery/zeta-node
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN make install-smoketest