FROM golang:1.20-bullseye

ENV GOPATH /go
ENV GOOS=linux
ENV CGO_ENABLED=1

RUN apt-get update
RUN apt install git make
RUN ssh-keygen -b 2048 -t rsa -f /root/.ssh/localtest.pem -q -N ""

WORKDIR /go/delivery/zeta-node
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN make install
#RUN make install-smoketest