FROM golang:1.20-alpine3.18 as builder

ENV GOPATH /go
ENV GOOS=linux
ENV CGO_ENABLED=1

WORKDIR /go/delivery/zeta-node

RUN apk update && \
    apk --no-cache add git make build-base jq openssh libusb-dev linux-headers bash curl tmux

COPY go.mod .
COPY go.sum .

RUN --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    make install

RUN cp /go/bin/zetaclientd /usr/local/bin
RUN cp /go/bin/zetacored /usr/local/bin
RUN cp /go/bin/zetae2e /usr/local/bin

#BUILD MAIN BINARY IMAGE
FROM golang:1.20-alpine

RUN apk --no-cache add jq bash curl wget nano tmux

COPY --chmod=765 --from=builder /usr/local/bin/zetaclientd /usr/local/bin/zetaclientd
COPY --chmod=765 --from=builder /usr/local/bin/zetacored /usr/local/bin/zetacored

WORKDIR /root/zetachain/

EXPOSE 26657
EXPOSE 26656
EXPOSE 1317
EXPOSE 9090
