// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: observer/events.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventBallotCreated struct {
	MsgTypeUrl       string `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	BallotIdentifier string `protobuf:"bytes,2,opt,name=ballot_identifier,json=ballotIdentifier,proto3" json:"ballot_identifier,omitempty"`
	ObservationHash  string `protobuf:"bytes,3,opt,name=observation_hash,json=observationHash,proto3" json:"observation_hash,omitempty"`
	ObservationChain string `protobuf:"bytes,4,opt,name=observation_chain,json=observationChain,proto3" json:"observation_chain,omitempty"`
	BallotType       string `protobuf:"bytes,5,opt,name=ballot_type,json=ballotType,proto3" json:"ballot_type,omitempty"`
}

func (m *EventBallotCreated) Reset()         { *m = EventBallotCreated{} }
func (m *EventBallotCreated) String() string { return proto.CompactTextString(m) }
func (*EventBallotCreated) ProtoMessage()    {}
func (*EventBallotCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1ca57368474456, []int{0}
}
func (m *EventBallotCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBallotCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBallotCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBallotCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBallotCreated.Merge(m, src)
}
func (m *EventBallotCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBallotCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBallotCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBallotCreated proto.InternalMessageInfo

func (m *EventBallotCreated) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *EventBallotCreated) GetBallotIdentifier() string {
	if m != nil {
		return m.BallotIdentifier
	}
	return ""
}

func (m *EventBallotCreated) GetObservationHash() string {
	if m != nil {
		return m.ObservationHash
	}
	return ""
}

func (m *EventBallotCreated) GetObservationChain() string {
	if m != nil {
		return m.ObservationChain
	}
	return ""
}

func (m *EventBallotCreated) GetBallotType() string {
	if m != nil {
		return m.BallotType
	}
	return ""
}

type EventKeygenBlockUpdated struct {
	MsgTypeUrl    string `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	KeygenBlock   string `protobuf:"bytes,2,opt,name=keygen_block,json=keygenBlock,proto3" json:"keygen_block,omitempty"`
	KeygenPubkeys string `protobuf:"bytes,3,opt,name=keygen_pubkeys,json=keygenPubkeys,proto3" json:"keygen_pubkeys,omitempty"`
}

func (m *EventKeygenBlockUpdated) Reset()         { *m = EventKeygenBlockUpdated{} }
func (m *EventKeygenBlockUpdated) String() string { return proto.CompactTextString(m) }
func (*EventKeygenBlockUpdated) ProtoMessage()    {}
func (*EventKeygenBlockUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1ca57368474456, []int{1}
}
func (m *EventKeygenBlockUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventKeygenBlockUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventKeygenBlockUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventKeygenBlockUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventKeygenBlockUpdated.Merge(m, src)
}
func (m *EventKeygenBlockUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventKeygenBlockUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventKeygenBlockUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventKeygenBlockUpdated proto.InternalMessageInfo

func (m *EventKeygenBlockUpdated) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *EventKeygenBlockUpdated) GetKeygenBlock() string {
	if m != nil {
		return m.KeygenBlock
	}
	return ""
}

func (m *EventKeygenBlockUpdated) GetKeygenPubkeys() string {
	if m != nil {
		return m.KeygenPubkeys
	}
	return ""
}

func init() {
	proto.RegisterType((*EventBallotCreated)(nil), "zetachain.zetacore.observer.EventBallotCreated")
	proto.RegisterType((*EventKeygenBlockUpdated)(nil), "zetachain.zetacore.observer.EventKeygenBlockUpdated")
}

func init() { proto.RegisterFile("observer/events.proto", fileDescriptor_1f1ca57368474456) }

var fileDescriptor_1f1ca57368474456 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4f, 0x4b, 0xc3, 0x30,
	0x1c, 0x5d, 0xfc, 0x07, 0x66, 0x53, 0x67, 0x50, 0x56, 0x26, 0xd4, 0x39, 0x10, 0x14, 0xb1, 0x39,
	0xf8, 0x0d, 0x36, 0x04, 0x87, 0x17, 0x11, 0x77, 0xf1, 0x52, 0xd2, 0xed, 0x67, 0x5b, 0xda, 0x35,
	0x25, 0xc9, 0x86, 0xf5, 0xee, 0xdd, 0x8f, 0xe5, 0x71, 0x47, 0x0f, 0x1e, 0x64, 0xfb, 0x22, 0x92,
	0xa4, 0x9b, 0x3d, 0x7a, 0x0b, 0xef, 0xf7, 0xde, 0xcb, 0x7b, 0x3c, 0x7c, 0xcc, 0x03, 0x09, 0x62,
	0x06, 0x82, 0xc2, 0x0c, 0x32, 0x25, 0xbd, 0x5c, 0x70, 0xc5, 0xc9, 0xc9, 0x1b, 0x28, 0x36, 0x8a,
	0x58, 0x9c, 0x79, 0xe6, 0xc5, 0x05, 0x78, 0x2b, 0x66, 0xfb, 0x28, 0xe4, 0x21, 0x37, 0x3c, 0xaa,
	0x5f, 0x56, 0xd2, 0x6e, 0xad, 0x9d, 0x56, 0x0f, 0x7b, 0xe8, 0x7e, 0x23, 0x4c, 0x6e, 0xb5, 0x79,
	0x8f, 0xa5, 0x29, 0x57, 0x7d, 0x01, 0x4c, 0xc1, 0x98, 0x74, 0x70, 0x63, 0x22, 0x43, 0x5f, 0x15,
	0x39, 0xf8, 0x53, 0x91, 0x3a, 0xa8, 0x83, 0x2e, 0x76, 0x1f, 0xf1, 0x44, 0x86, 0x4f, 0x45, 0x0e,
	0x43, 0x91, 0x92, 0x2b, 0x7c, 0x18, 0x18, 0x89, 0x1f, 0x8f, 0x21, 0x53, 0xf1, 0x4b, 0x0c, 0xc2,
	0xd9, 0x30, 0xb4, 0xa6, 0x3d, 0x0c, 0xd6, 0x38, 0xb9, 0xc4, 0x4d, 0xfb, 0x2f, 0x53, 0x31, 0xcf,
	0xfc, 0x88, 0xc9, 0xc8, 0xd9, 0x34, 0xdc, 0x83, 0x0a, 0x7e, 0xc7, 0x64, 0xa4, 0x7d, 0xab, 0x54,
	0x53, 0xd3, 0xd9, 0xb2, 0xbe, 0x95, 0x43, 0x5f, 0xe3, 0xe4, 0x14, 0xd7, 0xcb, 0x10, 0x3a, 0xa9,
	0xb3, 0x6d, 0x53, 0x5a, 0x48, 0x07, 0xed, 0xbe, 0x23, 0xdc, 0x32, 0xf5, 0xee, 0xa1, 0x08, 0x21,
	0xeb, 0xa5, 0x7c, 0x94, 0x0c, 0xf3, 0xf1, 0x3f, 0x3b, 0x9e, 0xe1, 0x46, 0x62, 0x74, 0x7e, 0xa0,
	0x85, 0x65, 0xbd, 0x7a, 0xf2, 0xe7, 0x45, 0xce, 0xf1, 0x7e, 0x49, 0xc9, 0xa7, 0x41, 0x02, 0x85,
	0x2c, 0x7b, 0xed, 0x59, 0xf4, 0xc1, 0x82, 0xbd, 0xc1, 0xe7, 0xc2, 0x45, 0xf3, 0x85, 0x8b, 0x7e,
	0x16, 0x2e, 0xfa, 0x58, 0xba, 0xb5, 0xf9, 0xd2, 0xad, 0x7d, 0x2d, 0xdd, 0xda, 0x33, 0x0d, 0x63,
	0x15, 0x4d, 0x03, 0x6f, 0xc4, 0x27, 0x54, 0xaf, 0x79, 0x6d, 0x1a, 0xd3, 0xd5, 0xb0, 0xf4, 0x75,
	0xbd, 0x18, 0xd5, 0x49, 0x65, 0xb0, 0x63, 0x86, 0xbb, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0xbf, 0x05, 0xd1, 0x1d, 0x02, 0x00, 0x00,
}

func (m *EventBallotCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBallotCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBallotCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BallotType) > 0 {
		i -= len(m.BallotType)
		copy(dAtA[i:], m.BallotType)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.BallotType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ObservationChain) > 0 {
		i -= len(m.ObservationChain)
		copy(dAtA[i:], m.ObservationChain)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ObservationChain)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ObservationHash) > 0 {
		i -= len(m.ObservationHash)
		copy(dAtA[i:], m.ObservationHash)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ObservationHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BallotIdentifier) > 0 {
		i -= len(m.BallotIdentifier)
		copy(dAtA[i:], m.BallotIdentifier)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.BallotIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventKeygenBlockUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventKeygenBlockUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventKeygenBlockUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.KeygenPubkeys) > 0 {
		i -= len(m.KeygenPubkeys)
		copy(dAtA[i:], m.KeygenPubkeys)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.KeygenPubkeys)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.KeygenBlock) > 0 {
		i -= len(m.KeygenBlock)
		copy(dAtA[i:], m.KeygenBlock)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.KeygenBlock)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventBallotCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.BallotIdentifier)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ObservationHash)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ObservationChain)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.BallotType)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventKeygenBlockUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.KeygenBlock)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.KeygenPubkeys)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventBallotCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBallotCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBallotCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BallotIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservationHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservationChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservationChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BallotType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventKeygenBlockUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventKeygenBlockUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventKeygenBlockUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeygenBlock = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenPubkeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeygenPubkeys = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
