// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file zetachain/zetacore/fungible/foreign_coins.proto (package zetachain.zetacore.fungible, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { CoinType } from "../pkg/coin/coin_pb";
import { file_zetachain_zetacore_pkg_coin_coin } from "../pkg/coin/coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zetachain/zetacore/fungible/foreign_coins.proto.
 */
export const file_zetachain_zetacore_fungible_foreign_coins: GenFile = /*@__PURE__*/
  fileDesc("Ci96ZXRhY2hhaW4vemV0YWNvcmUvZnVuZ2libGUvZm9yZWlnbl9jb2lucy5wcm90bxIbemV0YWNoYWluLnpldGFjb3JlLmZ1bmdpYmxlIp8CCgxGb3JlaWduQ29pbnMSHgoWenJjMjBfY29udHJhY3RfYWRkcmVzcxgCIAEoCRINCgVhc3NldBgDIAEoCRIYChBmb3JlaWduX2NoYWluX2lkGAQgASgDEhAKCGRlY2ltYWxzGAUgASgNEgwKBG5hbWUYBiABKAkSDgoGc3ltYm9sGAcgASgJEjgKCWNvaW5fdHlwZRgIIAEoDjIlLnpldGFjaGFpbi56ZXRhY29yZS5wa2cuY29pbi5Db2luVHlwZRIVCglnYXNfbGltaXQYCSABKARCAhgBEg4KBnBhdXNlZBgKIAEoCBI1Cg1saXF1aWRpdHlfY2FwGAsgASgJQh7I3h8A2t4fFmNvc21vc3Nkay5pby9tYXRoLlVpbnRC7wEKH2NvbS56ZXRhY2hhaW4uemV0YWNvcmUuZnVuZ2libGVCEUZvcmVpZ25Db2luc1Byb3RvUAFaK2dpdGh1Yi5jb20vemV0YS1jaGFpbi9ub2RlL3gvZnVuZ2libGUvdHlwZXOiAgNaWkaqAhtaZXRhY2hhaW4uWmV0YWNvcmUuRnVuZ2libGXKAhtaZXRhY2hhaW5cWmV0YWNvcmVcRnVuZ2libGXiAidaZXRhY2hhaW5cWmV0YWNvcmVcRnVuZ2libGVcR1BCTWV0YWRhdGHqAh1aZXRhY2hhaW46OlpldGFjb3JlOjpGdW5naWJsZWIGcHJvdG8z", [file_gogoproto_gogo, file_zetachain_zetacore_pkg_coin_coin]);

/**
 * @generated from message zetachain.zetacore.fungible.ForeignCoins
 */
export type ForeignCoins = Message<"zetachain.zetacore.fungible.ForeignCoins"> & {
  /**
   *  string index = 1;
   *
   * index
   *
   * @generated from field: string zrc20_contract_address = 2;
   */
  zrc20ContractAddress: string;

  /**
   * @generated from field: string asset = 3;
   */
  asset: string;

  /**
   * @generated from field: int64 foreign_chain_id = 4;
   */
  foreignChainId: bigint;

  /**
   * @generated from field: uint32 decimals = 5;
   */
  decimals: number;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: string symbol = 7;
   */
  symbol: string;

  /**
   * @generated from field: zetachain.zetacore.pkg.coin.CoinType coin_type = 8;
   */
  coinType: CoinType;

  /**
   * Deprecated: value stored in the zrc20 smart contract is used instead
   *
   * @generated from field: uint64 gas_limit = 9 [deprecated = true];
   * @deprecated
   */
  gasLimit: bigint;

  /**
   * @generated from field: bool paused = 10;
   */
  paused: boolean;

  /**
   * @generated from field: string liquidity_cap = 11;
   */
  liquidityCap: string;
};

/**
 * Describes the message zetachain.zetacore.fungible.ForeignCoins.
 * Use `create(ForeignCoinsSchema)` to create a new message.
 */
export const ForeignCoinsSchema: GenMessage<ForeignCoins> = /*@__PURE__*/
  messageDesc(file_zetachain_zetacore_fungible_foreign_coins, 0);

