// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file observer/tx.proto (package zetachain.zetacore.observer, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { CoreParams } from "./params_pb.js";
import type { ObservationType } from "./observer_pb.js";
import type { Blame } from "./blame_pb.js";

/**
 * @generated from message zetachain.zetacore.observer.MsgUpdateCoreParams
 */
export declare class MsgUpdateCoreParams extends Message<MsgUpdateCoreParams> {
  /**
   * @generated from field: string creator = 1;
   */
  creator: string;

  /**
   * @generated from field: zetachain.zetacore.observer.CoreParams coreParams = 2;
   */
  coreParams?: CoreParams;

  constructor(data?: PartialMessage<MsgUpdateCoreParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgUpdateCoreParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateCoreParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateCoreParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateCoreParams;

  static equals(a: MsgUpdateCoreParams | PlainMessage<MsgUpdateCoreParams> | undefined, b: MsgUpdateCoreParams | PlainMessage<MsgUpdateCoreParams> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgUpdateCoreParamsResponse
 */
export declare class MsgUpdateCoreParamsResponse extends Message<MsgUpdateCoreParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateCoreParamsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgUpdateCoreParamsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateCoreParamsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateCoreParamsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateCoreParamsResponse;

  static equals(a: MsgUpdateCoreParamsResponse | PlainMessage<MsgUpdateCoreParamsResponse> | undefined, b: MsgUpdateCoreParamsResponse | PlainMessage<MsgUpdateCoreParamsResponse> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgAddObserver
 */
export declare class MsgAddObserver extends Message<MsgAddObserver> {
  /**
   * @generated from field: string creator = 1;
   */
  creator: string;

  /**
   * @generated from field: int64 chain_id = 2;
   */
  chainId: bigint;

  /**
   * @generated from field: zetachain.zetacore.observer.ObservationType observationType = 3;
   */
  observationType: ObservationType;

  constructor(data?: PartialMessage<MsgAddObserver>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgAddObserver";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddObserver;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddObserver;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddObserver;

  static equals(a: MsgAddObserver | PlainMessage<MsgAddObserver> | undefined, b: MsgAddObserver | PlainMessage<MsgAddObserver> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgAddObserverResponse
 */
export declare class MsgAddObserverResponse extends Message<MsgAddObserverResponse> {
  constructor(data?: PartialMessage<MsgAddObserverResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgAddObserverResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddObserverResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddObserverResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddObserverResponse;

  static equals(a: MsgAddObserverResponse | PlainMessage<MsgAddObserverResponse> | undefined, b: MsgAddObserverResponse | PlainMessage<MsgAddObserverResponse> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgAddBlameVote
 */
export declare class MsgAddBlameVote extends Message<MsgAddBlameVote> {
  /**
   * @generated from field: string creator = 1;
   */
  creator: string;

  /**
   * @generated from field: int64 chain_id = 2;
   */
  chainId: bigint;

  /**
   * @generated from field: zetachain.zetacore.observer.Blame blame_info = 3;
   */
  blameInfo?: Blame;

  constructor(data?: PartialMessage<MsgAddBlameVote>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgAddBlameVote";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddBlameVote;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddBlameVote;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddBlameVote;

  static equals(a: MsgAddBlameVote | PlainMessage<MsgAddBlameVote> | undefined, b: MsgAddBlameVote | PlainMessage<MsgAddBlameVote> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgAddBlameVoteResponse
 */
export declare class MsgAddBlameVoteResponse extends Message<MsgAddBlameVoteResponse> {
  constructor(data?: PartialMessage<MsgAddBlameVoteResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgAddBlameVoteResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddBlameVoteResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddBlameVoteResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddBlameVoteResponse;

  static equals(a: MsgAddBlameVoteResponse | PlainMessage<MsgAddBlameVoteResponse> | undefined, b: MsgAddBlameVoteResponse | PlainMessage<MsgAddBlameVoteResponse> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgUpdatePermissionFlags
 */
export declare class MsgUpdatePermissionFlags extends Message<MsgUpdatePermissionFlags> {
  /**
   * @generated from field: string creator = 1;
   */
  creator: string;

  /**
   * @generated from field: bool isInboundEnabled = 3;
   */
  isInboundEnabled: boolean;

  constructor(data?: PartialMessage<MsgUpdatePermissionFlags>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgUpdatePermissionFlags";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdatePermissionFlags;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdatePermissionFlags;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdatePermissionFlags;

  static equals(a: MsgUpdatePermissionFlags | PlainMessage<MsgUpdatePermissionFlags> | undefined, b: MsgUpdatePermissionFlags | PlainMessage<MsgUpdatePermissionFlags> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgUpdatePermissionFlagsResponse
 */
export declare class MsgUpdatePermissionFlagsResponse extends Message<MsgUpdatePermissionFlagsResponse> {
  constructor(data?: PartialMessage<MsgUpdatePermissionFlagsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgUpdatePermissionFlagsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdatePermissionFlagsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdatePermissionFlagsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdatePermissionFlagsResponse;

  static equals(a: MsgUpdatePermissionFlagsResponse | PlainMessage<MsgUpdatePermissionFlagsResponse> | undefined, b: MsgUpdatePermissionFlagsResponse | PlainMessage<MsgUpdatePermissionFlagsResponse> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgUpdateKeygen
 */
export declare class MsgUpdateKeygen extends Message<MsgUpdateKeygen> {
  /**
   * @generated from field: string creator = 1;
   */
  creator: string;

  /**
   * @generated from field: int64 block = 2;
   */
  block: bigint;

  constructor(data?: PartialMessage<MsgUpdateKeygen>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgUpdateKeygen";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateKeygen;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateKeygen;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateKeygen;

  static equals(a: MsgUpdateKeygen | PlainMessage<MsgUpdateKeygen> | undefined, b: MsgUpdateKeygen | PlainMessage<MsgUpdateKeygen> | undefined): boolean;
}

/**
 * @generated from message zetachain.zetacore.observer.MsgUpdateKeygenResponse
 */
export declare class MsgUpdateKeygenResponse extends Message<MsgUpdateKeygenResponse> {
  constructor(data?: PartialMessage<MsgUpdateKeygenResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zetachain.zetacore.observer.MsgUpdateKeygenResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateKeygenResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateKeygenResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateKeygenResponse;

  static equals(a: MsgUpdateKeygenResponse | PlainMessage<MsgUpdateKeygenResponse> | undefined, b: MsgUpdateKeygenResponse | PlainMessage<MsgUpdateKeygenResponse> | undefined): boolean;
}

