# Use the official Go Ethereum image
FROM ethereum/client-go:latest

# Expose the ports (8545 for JSON-RPC, 8546 for WebSocket, 30303 for P2P)
EXPOSE 8545 8546 30303

# Set the entrypoint to start Geth
ENTRYPOINT ["geth"]
