/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ZetaReceiverMock,
  ZetaReceiverMockInterface,
} from "../../../contracts/testing/ZetaReceiverMock";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "destinationAddress",
        type: "address",
      },
    ],
    name: "MockOnZetaMessage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "originSenderAddress",
        type: "address",
      },
    ],
    name: "MockOnZetaRevert",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "originSenderAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "originChainId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "destinationAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "zetaAmount",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct ZetaInterfaces.ZetaMessage",
        name: "_zetaMessage",
        type: "tuple",
      },
    ],
    name: "onZetaMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "originSenderAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "originChainId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "destinationAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "destinationChainId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "zetaAmount",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct ZetaInterfaces.ZetaRevert",
        name: "_zetaRevert",
        type: "tuple",
      },
    ],
    name: "onZetaRevert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102aa806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633749c51a1461003b5780633ff0693c14610057575b600080fd5b6100556004803603810190610050919061017f565b610073565b005b610071600480360381019061006c91906101c0565b6100bf565b005b7f72a301dee3abcbe15615f3e253229bf4b4f508460603d674991c9a777b833c6e8160400160208101906100a79190610156565b6040516100b49190610210565b60405180910390a150565b7f53bd04e26f94f13ff43da96839541821041c309c6f624712192cbe3a2d133cc48160000160208101906100f39190610156565b6040516101009190610210565b60405180910390a150565b60008135905061011a8161025d565b92915050565b600060a0828403121561013257600080fd5b81905092915050565b600060c0828403121561014d57600080fd5b81905092915050565b60006020828403121561016857600080fd5b60006101768482850161010b565b91505092915050565b60006020828403121561019157600080fd5b600082013567ffffffffffffffff8111156101ab57600080fd5b6101b784828501610120565b91505092915050565b6000602082840312156101d257600080fd5b600082013567ffffffffffffffff8111156101ec57600080fd5b6101f88482850161013b565b91505092915050565b61020a8161022b565b82525050565b60006020820190506102256000830184610201565b92915050565b60006102368261023d565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6102668161022b565b811461027157600080fd5b5056fea26469706673582212206a804eddede7d7ea1fe604804be60dbbaf496aeaa8971548faf8a83dd1edf9a264736f6c63430008040033";

type ZetaReceiverMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ZetaReceiverMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ZetaReceiverMock__factory extends ContractFactory {
  constructor(...args: ZetaReceiverMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ZetaReceiverMock> {
    return super.deploy(overrides || {}) as Promise<ZetaReceiverMock>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ZetaReceiverMock {
    return super.attach(address) as ZetaReceiverMock;
  }
  override connect(signer: Signer): ZetaReceiverMock__factory {
    return super.connect(signer) as ZetaReceiverMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ZetaReceiverMockInterface {
    return new utils.Interface(_abi) as ZetaReceiverMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ZetaReceiverMock {
    return new Contract(address, _abi, signerOrProvider) as ZetaReceiverMock;
  }
}
