// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zetachain/zetacore/pkg/chains/chains.proto

package chains

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReceiveStatus int32

const (
	ReceiveStatus_Created ReceiveStatus = 0
	ReceiveStatus_Success ReceiveStatus = 1
	ReceiveStatus_Failed  ReceiveStatus = 2
)

var ReceiveStatus_name = map[int32]string{
	0: "Created",
	1: "Success",
	2: "Failed",
}

var ReceiveStatus_value = map[string]int32{
	"Created": 0,
	"Success": 1,
	"Failed":  2,
}

func (x ReceiveStatus) String() string {
	return proto.EnumName(ReceiveStatus_name, int32(x))
}

func (ReceiveStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_236b85e7bff6130d, []int{0}
}

type ChainName int32

const (
	ChainName_empty           ChainName = 0
	ChainName_eth_mainnet     ChainName = 1
	ChainName_zeta_mainnet    ChainName = 2
	ChainName_btc_mainnet     ChainName = 3
	ChainName_polygon_mainnet ChainName = 4
	ChainName_bsc_mainnet     ChainName = 5
	ChainName_goerli_testnet  ChainName = 6
	ChainName_mumbai_testnet  ChainName = 7
	ChainName_ganache_testnet ChainName = 8
	ChainName_baobab_testnet  ChainName = 9
	ChainName_bsc_testnet     ChainName = 10
	ChainName_zeta_testnet    ChainName = 11
	ChainName_btc_testnet     ChainName = 12
	ChainName_sepolia_testnet ChainName = 13
	ChainName_goerli_localnet ChainName = 14
	ChainName_btc_regtest     ChainName = 15
	ChainName_amoy_testnet    ChainName = 16
)

var ChainName_name = map[int32]string{
	0:  "empty",
	1:  "eth_mainnet",
	2:  "zeta_mainnet",
	3:  "btc_mainnet",
	4:  "polygon_mainnet",
	5:  "bsc_mainnet",
	6:  "goerli_testnet",
	7:  "mumbai_testnet",
	8:  "ganache_testnet",
	9:  "baobab_testnet",
	10: "bsc_testnet",
	11: "zeta_testnet",
	12: "btc_testnet",
	13: "sepolia_testnet",
	14: "goerli_localnet",
	15: "btc_regtest",
	16: "amoy_testnet",
}

var ChainName_value = map[string]int32{
	"empty":           0,
	"eth_mainnet":     1,
	"zeta_mainnet":    2,
	"btc_mainnet":     3,
	"polygon_mainnet": 4,
	"bsc_mainnet":     5,
	"goerli_testnet":  6,
	"mumbai_testnet":  7,
	"ganache_testnet": 8,
	"baobab_testnet":  9,
	"bsc_testnet":     10,
	"zeta_testnet":    11,
	"btc_testnet":     12,
	"sepolia_testnet": 13,
	"goerli_localnet": 14,
	"btc_regtest":     15,
	"amoy_testnet":    16,
}

func (x ChainName) String() string {
	return proto.EnumName(ChainName_name, int32(x))
}

func (ChainName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_236b85e7bff6130d, []int{1}
}

type Chain struct {
	ChainName ChainName `protobuf:"varint,1,opt,name=chain_name,json=chainName,proto3,enum=zetachain.zetacore.pkg.chains.ChainName" json:"chain_name,omitempty"`
	ChainId   int64     `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_236b85e7bff6130d, []int{0}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return m.Size()
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetChainName() ChainName {
	if m != nil {
		return m.ChainName
	}
	return ChainName_empty
}

func (m *Chain) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func init() {
	proto.RegisterEnum("zetachain.zetacore.pkg.chains.ReceiveStatus", ReceiveStatus_name, ReceiveStatus_value)
	proto.RegisterEnum("zetachain.zetacore.pkg.chains.ChainName", ChainName_name, ChainName_value)
	proto.RegisterType((*Chain)(nil), "zetachain.zetacore.pkg.chains.Chain")
}

func init() {
	proto.RegisterFile("zetachain/zetacore/pkg/chains/chains.proto", fileDescriptor_236b85e7bff6130d)
}

var fileDescriptor_236b85e7bff6130d = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xb1, 0x8e, 0x13, 0x31,
	0x10, 0x86, 0xd7, 0xb9, 0x4b, 0x72, 0x99, 0xdc, 0x25, 0x96, 0xa1, 0x38, 0x4e, 0x62, 0x75, 0xa2,
	0x0a, 0x91, 0xd8, 0x48, 0x50, 0xd2, 0x11, 0x09, 0x44, 0x43, 0x91, 0xeb, 0x68, 0x22, 0xaf, 0x33,
	0x72, 0xac, 0xac, 0xd7, 0xab, 0x5d, 0x2f, 0x52, 0x78, 0x0a, 0x1e, 0x82, 0x82, 0x47, 0xb9, 0x32,
	0x25, 0x25, 0x4a, 0x5e, 0x04, 0xd9, 0x8b, 0x9d, 0x8a, 0xab, 0x32, 0xfe, 0xf2, 0xcd, 0x3f, 0xa3,
	0xd5, 0xc0, 0xfc, 0x3b, 0x5a, 0x2e, 0xb6, 0x5c, 0x95, 0x0b, 0x5f, 0x99, 0x1a, 0x17, 0xd5, 0x4e,
	0x2e, 0x3c, 0x6a, 0xfe, 0xfd, 0x64, 0x55, 0x6d, 0xac, 0x61, 0x2f, 0xa3, 0x9b, 0x05, 0x37, 0xab,
	0x76, 0x32, 0xeb, 0xa4, 0xbb, 0xe7, 0xd2, 0x48, 0xe3, 0xcd, 0x85, 0xab, 0xba, 0xa6, 0x57, 0x3b,
	0xe8, 0x2f, 0xdd, 0xff, 0xec, 0x13, 0x80, 0x17, 0xd7, 0x25, 0xd7, 0x78, 0x4b, 0xee, 0xc9, 0x6c,
	0xf2, 0x76, 0x96, 0x3d, 0x19, 0x99, 0xf9, 0xce, 0x2f, 0x5c, 0xe3, 0x6a, 0x24, 0x42, 0xc9, 0x5e,
	0xc0, 0x55, 0x17, 0xa4, 0x36, 0xb7, 0xbd, 0x7b, 0x32, 0xbb, 0x58, 0x0d, 0xfd, 0xfb, 0xf3, 0x66,
	0xfe, 0x1e, 0x6e, 0x56, 0x28, 0x50, 0x7d, 0xc3, 0x07, 0xcb, 0x6d, 0xdb, 0xb0, 0x31, 0x0c, 0x97,
	0x35, 0x72, 0x8b, 0x1b, 0x9a, 0xb8, 0xc7, 0x43, 0x2b, 0x04, 0x36, 0x0d, 0x25, 0x0c, 0x60, 0xf0,
	0x91, 0xab, 0x02, 0x37, 0xb4, 0x77, 0x77, 0xf9, 0xeb, 0x67, 0x4a, 0xe6, 0x8f, 0x3d, 0x18, 0xc5,
	0x81, 0x6c, 0x04, 0x7d, 0xd4, 0x95, 0xdd, 0xd3, 0x84, 0x4d, 0x61, 0x8c, 0x76, 0xbb, 0xd6, 0x5c,
	0x95, 0x25, 0x5a, 0x4a, 0x18, 0x85, 0x6b, 0xb7, 0x6d, 0x24, 0x3d, 0xa7, 0xe4, 0x56, 0x44, 0x70,
	0xc1, 0x9e, 0xc1, 0xb4, 0x32, 0xc5, 0x5e, 0x9a, 0x32, 0xc2, 0x4b, 0x6f, 0x35, 0x67, 0xab, 0xcf,
	0x18, 0x4c, 0xa4, 0xc1, 0xba, 0x50, 0x6b, 0x8b, 0x8d, 0x75, 0x6c, 0xe0, 0x98, 0x6e, 0x75, 0xce,
	0xcf, 0x6c, 0xe8, 0xd2, 0x24, 0x2f, 0xb9, 0xd8, 0x62, 0x84, 0x57, 0x4e, 0xcc, 0xb9, 0xc9, 0x79,
	0x1e, 0xd9, 0x28, 0x4c, 0x08, 0x00, 0xe2, 0xaa, 0x81, 0x8c, 0xc3, 0xaa, 0x01, 0x5c, 0xbb, 0xf0,
	0x06, 0x2b, 0x53, 0xa8, 0xb3, 0x75, 0xe3, 0x27, 0x76, 0x9b, 0x15, 0x46, 0xf0, 0xc2, 0xc1, 0x49,
	0x68, 0xad, 0x51, 0x3a, 0x91, 0x4e, 0x5d, 0x3a, 0xd7, 0x66, 0x1f, 0xfb, 0x68, 0xf7, 0x29, 0x3f,
	0x2c, 0x1f, 0x8f, 0x29, 0x39, 0x1c, 0x53, 0xf2, 0xe7, 0x98, 0x92, 0x1f, 0xa7, 0x34, 0x39, 0x9c,
	0xd2, 0xe4, 0xf7, 0x29, 0x4d, 0xbe, 0xbe, 0x96, 0xca, 0x6e, 0xdb, 0x3c, 0x13, 0x46, 0xfb, 0x83,
	0x7b, 0xf3, 0xdf, 0xdb, 0xcb, 0x07, 0xfe, 0x80, 0xde, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x58,
	0x82, 0x1f, 0x90, 0xa3, 0x02, 0x00, 0x00,
}

func (m *Chain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainId != 0 {
		i = encodeVarintChains(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x10
	}
	if m.ChainName != 0 {
		i = encodeVarintChains(dAtA, i, uint64(m.ChainName))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintChains(dAtA []byte, offset int, v uint64) int {
	offset -= sovChains(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Chain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainName != 0 {
		n += 1 + sovChains(uint64(m.ChainName))
	}
	if m.ChainId != 0 {
		n += 1 + sovChains(uint64(m.ChainId))
	}
	return n
}

func sovChains(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChains(x uint64) (n int) {
	return sovChains(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Chain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChains
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			m.ChainName = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainName |= ChainName(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChains
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChains(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChains
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChains(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChains
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChains
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChains
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChains
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChains
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChains
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChains        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChains          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChains = fmt.Errorf("proto: unexpected end of group")
)
