package main

const ABI_MPI = `
	[
		 {
				"inputs":[
					 {
							"internalType":"address",
							"name":"zetaAddress",
							"type":"address"
					 },
					 {
							"internalType":"address",
							"name":"oracleAddress",
							"type":"address"
					 },
					 {
							"internalType":"address",
							"name":"_TSSAddress",
							"type":"address"
					 },
					 {
							"internalType":"address",
							"name":"_TSSAddressUpdater",
							"type":"address"
					 },
					 {
							"internalType":"address",
							"name":"_OracleUpdater",
							"type":"address"
					 }
				],
				"stateMutability":"nonpayable",
				"type":"constructor"
		 },
		 {
				"anonymous":false,
				"inputs":[
					 {
							"indexed":false,
							"internalType":"address",
							"name":"sender",
							"type":"address"
					 },
					 {
							"indexed":false,
							"internalType":"string",
							"name":"destChainID",
							"type":"string"
					 },
					 {
							"indexed":false,
							"internalType":"address",
							"name":"destContract",
							"type":"address"
					 },
					 {
							"indexed":false,
							"internalType":"uint256",
							"name":"zetaAmount",
							"type":"uint256"
					 },
					 {
							"indexed":false,
							"internalType":"uint256",
							"name":"gasLimit",
							"type":"uint256"
					 },
					 {
							"indexed":false,
							"internalType":"bytes",
							"name":"message",
							"type":"bytes"
					 },
					 {
							"indexed":false,
							"internalType":"bytes32",
							"name":"messageID",
							"type":"bytes32"
					 },
					 {
							"indexed":true,
							"internalType":"bytes32",
							"name":"utxoHash",
							"type":"bytes32"
					 }
				],
				"name":"ZetaMessageReceiveEvent",
				"type":"event"
		 },
		 {
				"anonymous":false,
				"inputs":[
					 {
							"indexed":false,
							"internalType":"address",
							"name":"sender",
							"type":"address"
					 },
					 {
							"indexed":false,
							"internalType":"string",
							"name":"destChainID",
							"type":"string"
					 },
					 {
							"indexed":false,
							"internalType":"string",
							"name":"destContract",
							"type":"string"
					 },
					 {
							"indexed":false,
							"internalType":"uint256",
							"name":"zetaAmount",
							"type":"uint256"
					 },
					 {
							"indexed":false,
							"internalType":"uint256",
							"name":"gasLimit",
							"type":"uint256"
					 },
					 {
							"indexed":false,
							"internalType":"bytes",
							"name":"message",
							"type":"bytes"
					 },
					 {
							"indexed":false,
							"internalType":"bytes32",
							"name":"messageID",
							"type":"bytes32"
					 }
				],
				"name":"ZetaMessageSendEvent",
				"type":"event"
		 },
		 {
				"inputs":[],
				"name":"OracleUpdater",
				"outputs":[
					 {
							"internalType":"address",
							"name":"",
							"type":"address"
					 }
				],
				"stateMutability":"view",
				"type":"function"
		 },
		 {
				"inputs":[],
				"name":"TSSAddress",
				"outputs":[
					 {
							"internalType":"address",
							"name":"",
							"type":"address"
					 }
				],
				"stateMutability":"view",
				"type":"function"
		 },
		 {
				"inputs":[],
				"name":"TSSAddressUpdater",
				"outputs":[
					 {
							"internalType":"address",
							"name":"",
							"type":"address"
					 }
				],
				"stateMutability":"view",
				"type":"function"
		 },
		 {
				"inputs":[
					 {
							"internalType":"address",
							"name":"newOracleAddres",
							"type":"address"
					 }
				],
				"name":"changeOracle",
				"outputs":[],
				"stateMutability":"nonpayable",
				"type":"function"
		 },
		 {
				"inputs":[],
				"name":"getLockedAmount",
				"outputs":[
					 {
							"internalType":"uint256",
							"name":"",
							"type":"uint256"
					 }
				],
				"stateMutability":"view",
				"type":"function"
		 },
		 {
				"inputs":[],
				"name":"renounceTSSAddressUpdater",
				"outputs":[],
				"stateMutability":"nonpayable",
				"type":"function"
		 },
		 {
				"inputs":[
					 {
							"internalType":"uint8",
							"name":"newFlexibility",
							"type":"uint8"
					 }
				],
				"name":"updateSupplyOracleFlexibility",
				"outputs":[],
				"stateMutability":"nonpayable",
				"type":"function"
		 },
		 {
				"inputs":[
					 {
							"internalType":"address",
							"name":"_address",
							"type":"address"
					 }
				],
				"name":"updateTSSAddress",
				"outputs":[],
				"stateMutability":"nonpayable",
				"type":"function"
		 },
		 {
				"inputs":[
					 {
							"internalType":"address",
							"name":"sender",
							"type":"address"
					 },
					 {
							"internalType":"string",
							"name":"destChainID",
							"type":"string"
					 },
					 {
							"internalType":"address",
							"name":"destContract",
							"type":"address"
					 },
					 {
							"internalType":"uint256",
							"name":"zetaAmount",
							"type":"uint256"
					 },
					 {
							"internalType":"uint256",
							"name":"gasLimit",
							"type":"uint256"
					 },
					 {
							"internalType":"bytes",
							"name":"message",
							"type":"bytes"
					 },
					 {
							"internalType":"bytes32",
							"name":"messageID",
							"type":"bytes32"
					 },
					 {
							"internalType":"bytes32",
							"name":"sendHash",
							"type":"bytes32"
					 }
				],
				"name":"zetaMessageReceive",
				"outputs":[],
				"stateMutability":"nonpayable",
				"type":"function"
		 },
		 {
				"inputs":[
					 {
							"internalType":"address",
							"name":"sender",
							"type":"address"
					 },
					 {
							"internalType":"string",
							"name":"destChainID",
							"type":"string"
					 },
					 {
							"internalType":"string",
							"name":"destContract",
							"type":"string"
					 },
					 {
							"internalType":"uint256",
							"name":"zetaAmount",
							"type":"uint256"
					 },
					 {
							"internalType":"uint256",
							"name":"gasLimit",
							"type":"uint256"
					 },
					 {
							"internalType":"bytes",
							"name":"message",
							"type":"bytes"
					 },
					 {
							"internalType":"bytes32",
							"name":"messageID",
							"type":"bytes32"
					 }
				],
				"name":"zetaMessageSend",
				"outputs":[],
				"stateMutability":"nonpayable",
				"type":"function"
		 }
	]`
